/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


#include <iostream> 


int main(){
	int currNum1 = 1;
	int currNum2 = 2; 
	int sum = 0; 
	while (currNum2 < 4000000){
		if ( currNum2 % 2 == 0 ){
			sum += currNum2; 
		}
		int temp = currNum1; 
		currNum1 = currNum2; 
		currNum2 += temp; 
	}


	std::cout << sum << std::endl; 
	return 0; 

}
